const puppeteer = require("puppeteer");
const { createClient } = require("@clickhouse/client");

require("dotenv").config();

const clickhouse = createClient({
    url: `http://${process.env.CLICKHOUSE_HOST || "localhost"}:${process.env.CLICKHOUSE_PORT || "8123"}`,
    database: process.env.CLICKHOUSE_DB || "analytics",
    username: process.env.CLICKHOUSE_USER || "analyst",
    password: process.env.CLICKHOUSE_PASSWORD || "analyst_password"
});

function getTableNameFromEnv(envName, defaultValue) {
    const tableName = process.env[envName] || defaultValue;

    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(tableName)) {
        throw new Error(`${envName} hanya boleh berisi huruf, angka, dan underscore, serta tidak boleh diawali angka.`);
    }

    return tableName;
}

const SURVEY_TABLE_NAME = getTableNameFromEnv("SURVEY_TABLE_NAME", "surveys");
const REGION_GROUP_TABLE_NAME = getTableNameFromEnv("REGION_GROUP_TABLE_NAME", "region_groups");
const LEVEL_TABLE_NAMES = Array.from({ length: 6 }, (_, index) => {
    const level = index + 1;
    return getTableNameFromEnv(`LEVEL_${level}_TABLE_NAME`, `level_${level}`);
});

function levelTableName(level) {
    return LEVEL_TABLE_NAMES[level - 1];
}

function toDateTime(value) {
    if (!value) {
        return null;
    }

    const date = new Date(value);
    if (Number.isNaN(date.getTime())) {
        return null;
    }

    return date.toISOString().slice(0, 19).replace("T", " ");
}

function toJson(value, defaultValue) {
    if (value === undefined || value === null) {
        return JSON.stringify(defaultValue);
    }

    return JSON.stringify(value);
}

function surveyRow(data) {
    return {
        id: data.id,
        unit: data.unit || null,
        name: data.name,
        description: data.description || null,
        programId: data.programId || null,
        userId: data.userId || null,
        isActive: data.isActive ? 1 : 0,
        panelType: data.panelType ? 1 : 0,
        areaType: data.areaType ? 1 : 0,
        updateListingType: data.updateListingType ? 1 : 0,
        canAddSample: data.canAddSample ? 1 : 0,
        isMultiPencacah: data.isMultiPencacah ? 1 : 0,
        geoLiveTracking: data.geoLiveTracking ? 1 : 0,
        geoRadius: data.geoRadius ?? null,
        geoAccuracy: data.geoAccuracy ?? null,
        surveySampleMethodId: data.surveySampleMethodId || null,
        surveyStepTypeId: data.surveyStepTypeId || null,
        surveyParentId: data.surveyParentId || null,
        cawiTokenAutoGenerated: data.cawiTokenAutoGenerated || null,
        html: data.html || null,
        htmlEmail: data.htmlEmail || null,
        htmlRejectionEmail: data.htmlRejectionEmail || null,
        htmlReceived: data.htmlReceived || null,
        imageServiceType: data.imageServiceType || null,
        imageServiceUrl: data.imageServiceUrl || null,
        regionGroupId: data.regionGroupId || null,
        surveyType: data.surveyType || null,
        backgroundRecord: data.backgroundRecord ? 1 : 0,
        smallestRegionType: data.smallestRegionType ?? null,
        ocawiAlias: data.ocawiAlias || null,
        cawiAuthenticationLink: data.cawiAuthenticationLink || null,
        papiValidationType: data.papiValidationType ? 1 : 0,
        collectionMethod: data.collectionMethod ?? null,
        formGearVersion: data.formGearVersion || null,
        pathOfflinePdfTemplate: data.pathOfflinePdfTemplate || null,
        typeRole: data.typeRole ?? null,
        showCawiReceipt: data.showCawiReceipt === null || data.showCawiReceipt === undefined ? null : (data.showCawiReceipt ? 1 : 0),
        autoAssignWhenUploadSample: data.autoAssignWhenUploadSample ? 1 : 0,
        cawiMaxAccess: data.cawiMaxAccess ?? null,
        isPublic: data.isPublic === null || data.isPublic === undefined ? null : (data.isPublic ? 1 : 0),
        surveyPeriods: toJson(data.surveyPeriods, []),
        surveyGlossaries: toJson(data.surveyGlossaries, []),
        surveyTemplates: toJson(data.surveyTemplates, []),
        surveyModeList: toJson(data.surveyModeList, []),
        surveyModes: toJson(data.surveyModes, []),
        raw: toJson(data, {}),
        createdAt: toDateTime(data.createdAt),
        updatedAt: toDateTime(data.updatedAt),
        inserted_at: toDateTime(new Date())
    };
}

function regionGroupRow(data) {
    return {
        id: data.id,
        levelCount: data.levelCount,
        smallestRegionLevel: data.smallestRegionLevel || null,
        groupName: data.groupName,
        isActive: data.isActive ? 1 : 0,
        isPublic: data.isPublic === null || data.isPublic === undefined ? null : (data.isPublic ? 1 : 0),
        createdBy: data.createdBy || null,
        updatedBy: data.updatedBy || null,
        createdDate: toDateTime(data.createdDate),
        updatedDate: toDateTime(data.updatedDate),
        userIds: toJson(data.userIds, []),
        level: toJson(data.level, []),
        raw: toJson(data, {}),
        inserted_at: toDateTime(new Date())
    };
}

function levelRow(data) {
    return {
        id: data.id,
        name: data.name || null,
        fullCode: data.fullCode || null,
        code: data.code || null,
        inserted_at: toDateTime(new Date())
    };
}

async function insertJsonEachRow(tableName, rows) {
    if (!Array.isArray(rows) || rows.length === 0) {
        return;
    }

    await clickhouse.insert({
        table: tableName,
        values: rows,
        format: "JSONEachRow"
    });
}

async function initializeClickHouse() {
    await clickhouse.command({
        query: `
        CREATE TABLE IF NOT EXISTS ${SURVEY_TABLE_NAME}
        (
            id String,
            unit Nullable(String),
            name String,
            description Nullable(String),
            programId Nullable(String),
            userId Nullable(String),
            isActive UInt8,
            panelType UInt8,
            areaType UInt8,
            updateListingType UInt8,
            canAddSample UInt8,
            isMultiPencacah UInt8,
            geoLiveTracking UInt8,
            geoRadius Nullable(Int32),
            geoAccuracy Nullable(Int32),
            surveySampleMethodId Nullable(String),
            surveyStepTypeId Nullable(String),
            surveyParentId Nullable(String),
            cawiTokenAutoGenerated Nullable(String),
            html Nullable(String),
            htmlEmail Nullable(String),
            htmlRejectionEmail Nullable(String),
            htmlReceived Nullable(String),
            imageServiceType Nullable(String),
            imageServiceUrl Nullable(String),
            regionGroupId Nullable(String),
            surveyType Nullable(String),
            backgroundRecord UInt8,
            smallestRegionType Nullable(Int32),
            ocawiAlias Nullable(String),
            cawiAuthenticationLink Nullable(String),
            papiValidationType UInt8,
            collectionMethod Nullable(Int32),
            formGearVersion Nullable(String),
            pathOfflinePdfTemplate Nullable(String),
            typeRole Nullable(Int32),
            showCawiReceipt Nullable(UInt8),
            autoAssignWhenUploadSample UInt8,
            cawiMaxAccess Nullable(Int32),
            isPublic Nullable(UInt8),
            surveyPeriods String,
            surveyGlossaries String,
            surveyTemplates String,
            surveyModeList String,
            surveyModes String,
            raw String,
            createdAt Nullable(DateTime),
            updatedAt Nullable(DateTime),
            inserted_at DateTime
        )
        ENGINE = ReplacingMergeTree(inserted_at)
        ORDER BY id
    `
    });

    await clickhouse.command({
        query: `
        CREATE TABLE IF NOT EXISTS ${REGION_GROUP_TABLE_NAME}
        (
            id String,
            levelCount Int32,
            smallestRegionLevel Nullable(String),
            groupName String,
            isActive UInt8,
            isPublic Nullable(UInt8),
            createdBy Nullable(String),
            updatedBy Nullable(String),
            createdDate Nullable(DateTime),
            updatedDate Nullable(DateTime),
            userIds String,
            level String,
            raw String,
            inserted_at DateTime
        )
        ENGINE = ReplacingMergeTree(inserted_at)
        ORDER BY id
    `
    });

    for (let i = 1; i <= 6; i++) {
        await clickhouse.command({
            query: `
            CREATE TABLE IF NOT EXISTS ${levelTableName(i)}
            (
                id String,
                name Nullable(String),
                fullCode Nullable(String),
                code Nullable(String),
                inserted_at DateTime
            )
            ENGINE = ReplacingMergeTree(inserted_at)
            ORDER BY id
        `
        });
    }
}

async function crawl_master_wilayah() {
    await initializeClickHouse();
    console.log("ClickHouse connected");

    const surveyId = process.env.SURVEY_ID;

    const browser = await puppeteer.launch({
        headless: false,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-web-security',
            '--disable-features=IsolateOrigins,site-per-process'
        ]
    });
    const page = await browser.newPage();

    // LOGIN
    await page.goto("https://fasih-sm.bps.go.id/oauth2/authorization/ics", {
        waitUntil: "networkidle2"
    });

    await page.type("#username", process.env.USERNAME_COMMUNITY);
    await page.type("#password", process.env.PASSWORD_COMMUNITY);
    await page.click("#kc-login");
    await page.waitForNavigation();

    // MASUK HALAMAN SURVEY
    await page.goto(
        "https://fasih-sm.bps.go.id/survey-collection/collect/" + surveyId,
        { waitUntil: "networkidle2" }
    );

    console.log("Survey INFO");

    const survey = await page.evaluate(async (surveyId) => {
        const res = await fetch(
            "https://fasih-sm.bps.go.id/survey/api/v1/surveys/" + surveyId,
            {
                method: "GET",
                credentials: "include",
                headers: { accept: "application/json" }
            }
        );
        return await res.json();
    }, surveyId);

    await insertJsonEachRow(SURVEY_TABLE_NAME, [surveyRow(survey.data)]);

    console.log("Download Master Wilayah");

    const groupId = survey.data.regionGroupId;

    // REGION METADATA
    let region_level = await page.evaluate(async (groupId) => {
        const res = await fetch(
            "https://fasih-sm.bps.go.id/region/api/v1/region-metadata?id=" + groupId,
            {
                method: "GET",
                credentials: "include",
                headers: { accept: "application/json" }
            }
        );
        return await res.json();
    }, groupId);

    await insertJsonEachRow(REGION_GROUP_TABLE_NAME, [regionGroupRow(region_level.data)]);

    const level_count = region_level.data.levelCount;

    // INIT STRUKTUR LEVEL
    for (let i = 0; i < level_count; i++) {
        if (!region_level.data.level[i]) {
            region_level.data.level[i] = {};
        }
        region_level.data.level[i].data = [];
    }

    let current_level = 1;

    while (current_level <= level_count) {
        console.log("download level " + current_level);

        // ================= LEVEL 1 =================
        if (current_level === 1) {
            const level = await page.evaluate(async (groupId) => {
                const res = await fetch(
                    "https://fasih-sm.bps.go.id/region/api/v1/region/level1?groupId=" + groupId,
                    {
                        method: "GET",
                        credentials: "include",
                        headers: { accept: "application/json" }
                    }
                );
                return await res.json();
            }, groupId);

            const filtered = [];

            for (const element of level.data || []) {
                if (element.fullCode == process.env.FULLCODE_REGION_1) {
                    filtered.push(element);
                }
            }

            region_level.data.level[0].data = filtered;

            await insertJsonEachRow(levelTableName(1), filtered.map(levelRow));
        }

        // ================= LEVEL > 1 =================
        else {
            const prevLevel = region_level.data.level[current_level - 2];
            const currLevel = region_level.data.level[current_level - 1];

            if (!prevLevel || !Array.isArray(prevLevel.data)) {
                console.log("Level sebelumnya kosong, stop.");
                break;
            }

            currLevel.data = [];

            for (const element of prevLevel.data) {
                const params = {
                    groupId: groupId
                };

                const key = `level${current_level - 1}Id`;
                params[key] = element.id;

                const level = await page.evaluate(
                    async ({ params, current_level }) => {
                        const key = `level${current_level - 1}Id`;

                        const url = `https://fasih-sm.bps.go.id/region/api/v1/region/level${current_level}?groupId=${params.groupId}&${key}=${params[key]}`;

                        const res = await fetch(url, {
                            method: "GET",
                            credentials: "include",
                            headers: { accept: "application/json" }
                        });

                        return await res.json();
                    },
                    { params, current_level }
                );

                const rows = level.data || [];
                currLevel.data.push(...rows);

                await insertJsonEachRow(levelTableName(current_level), rows.map(levelRow));
            }
        }
        current_level++;
    }

    console.log("Selesai download semua level");
    await browser.close();
    await clickhouse.close();
}

crawl_master_wilayah().catch(async (error) => {
    console.error(error);
    await clickhouse.close();
    process.exit(1);
});
