const { DataTypes } = require("sequelize");
const sequelize = require("../database");

const Survey = sequelize.define("Survey", {
    id: {
      type: DataTypes.UUID,
      primaryKey: true
    },

    unit: DataTypes.STRING,
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    description: DataTypes.TEXT,

    programId: DataTypes.UUID,
    userId: DataTypes.UUID,

    isActive: DataTypes.BOOLEAN,
    panelType: DataTypes.BOOLEAN,
    areaType: DataTypes.BOOLEAN,
    updateListingType: DataTypes.BOOLEAN,
    canAddSample: DataTypes.BOOLEAN,
    isMultiPencacah: DataTypes.BOOLEAN,

    geoLiveTracking: DataTypes.BOOLEAN,
    geoRadius: DataTypes.INTEGER,
    geoAccuracy: DataTypes.INTEGER,

    surveySampleMethodId: {
      type: DataTypes.UUID,
      allowNull: true
    },
    surveyStepTypeId: {
      type: DataTypes.UUID,
      allowNull: true
    },
    surveyParentId: {
      type: DataTypes.UUID,
      allowNull: true
    },

    cawiTokenAutoGenerated: {
      type: DataTypes.STRING,
      allowNull: true
    },

    html: {
      type: DataTypes.TEXT,
      allowNull: true
    },
    htmlEmail: DataTypes.TEXT,
    htmlRejectionEmail: DataTypes.TEXT,
    htmlReceived: DataTypes.TEXT,

    imageServiceType: DataTypes.STRING,
    imageServiceUrl: DataTypes.STRING,

    regionGroupId: DataTypes.UUID,

    surveyType: DataTypes.STRING,

    backgroundRecord: DataTypes.BOOLEAN,
    smallestRegionType: DataTypes.INTEGER,

    ocawiAlias: DataTypes.STRING,
    cawiAuthenticationLink: DataTypes.STRING,

    papiValidationType: DataTypes.BOOLEAN,
    collectionMethod: DataTypes.INTEGER,

    formGearVersion: DataTypes.STRING,
    pathOfflinePdfTemplate: DataTypes.STRING,

    typeRole: DataTypes.INTEGER,

    showCawiReceipt: {
      type: DataTypes.BOOLEAN,
      allowNull: true
    },

    autoAssignWhenUploadSample: DataTypes.BOOLEAN,
    cawiMaxAccess: DataTypes.INTEGER,

    isPublic: {
      type: DataTypes.BOOLEAN,
      allowNull: true
    },

    // 🔥 JSON fields (nested object)
    surveyPeriods: {
      type: DataTypes.JSON,
      allowNull: true,
      defaultValue: []
    },

    surveyGlossaries: {
      type: DataTypes.JSON,
      allowNull: true,
      defaultValue: []
    },

    surveyTemplates: {
      type: DataTypes.JSON,
      allowNull: true,
      defaultValue: []
    },

    surveyModeList: {
      type: DataTypes.JSON,
      allowNull: true,
      defaultValue: []
    },

    surveyModes: {
      type: DataTypes.JSON,
      allowNull: true,
      defaultValue: []
    },

    // 🧠 simpan raw API (best practice crawler)
    raw: {
      type: DataTypes.JSON,
      allowNull: true
    },

    createdAt: {
      type: DataTypes.DATE
    },

    updatedAt: {
      type: DataTypes.DATE
    }

  }, {
    tableName: "surveys_ngibar",
  });


module.exports = Survey;